import '../wrestler_editor/models.dart' show MoveAttribute, moveAttributeLabel;
import 'technique_deck_models.dart';

/// Technique Deck Builder画面を実際に試せるようにするための暫定サンプル
/// カタログ。
///
/// Technique Deck Rules専用の正式カードデータはまだ投入されていない
/// （docs/design/technique_deck_implementation_plan.md Phase 2「未完了」
/// 参照）。ここでは既存レスラー（`wrestler_akari` / `wrestler_jack`、
/// `lib/src/wrestler_editor/defaults.dart`）のIDを [TechniqueDeckTechniqueCard.
/// allowedWrestlerIds] の例として借用しつつ、画面の動作確認・自動生成の
/// テストに使える最小限のカード一式を用意する。**ゲームバランス調整済みの
/// 正式データではない。**
TechniqueDeckCardCatalog buildProvisionalTechniqueDeckCatalog() {
  const akari = 'wrestler_akari';
  const jack = 'wrestler_jack';
  const reina = 'wrestler_reina';
  const misaki = 'wrestler_misaki';

  final techniques = <TechniqueDeckTechniqueCard>[
    const TechniqueDeckTechniqueCard(
      id: 'td_normal_strike_1',
      name: 'ジャブ連打',
      category: TechniqueCardCategory.normal,
      attribute: MoveAttribute.strike,
      attackEnergyCost: {MoveAttribute.strike: 1},
      reversalEnergyCost: {MoveAttribute.strike: 1},
      power: 8,

      speed: 1,
      heatDelta: 5,
      description: '基本の打撃技。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_normal_throw_1',
      name: 'バックドロップ',
      category: TechniqueCardCategory.normal,
      attribute: MoveAttribute.throwMove,
      attackEnergyCost: {MoveAttribute.throwMove: 2},
      reversalEnergyCost: {MoveAttribute.throwMove: 1},
      power: 12,

      speed: 2,
      heatDelta: 6,
      targetState: TechniqueTargetState.stand,
      causesDown: true,
      hasPinEffect: true,
      kickOutThreshold: 20,
      kickOutHpRate: 0.5,
      description: '相手をダウンさせるスタンド限定の投げ技。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_normal_submission_1',
      name: 'アームロック',
      category: TechniqueCardCategory.normal,
      attribute: MoveAttribute.submission,
      attackEnergyCost: {MoveAttribute.submission: 2},
      reversalEnergyCost: {MoveAttribute.submission: 1},
      power: 6,

      speed: 1,
      heatDelta: 4,
      // Phase 6完了後のプレイテストで判明した「ダウン限定だと使う機会が
      // 無く一度も選ばれない」問題への対応（ユーザー指摘）。スタンドでも
      // 使用可能にしつつ、ダウン中に極めるとdownBonusPower分の追加威力
      // （関節技らしい「決まれば効く」性質）を持たせた。
      targetState: TechniqueTargetState.any,
      hasSubmissionEffect: true,
      giveUpThreshold: 20,
      giveUpHpCost: 10,
      downBonusPower: 6,
      description: '関節技。ダウン中の相手に極めると威力が上がる。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_normal_rough_1',
      name: '闘魂ビンタ',
      category: TechniqueCardCategory.normal,
      attribute: MoveAttribute.rough,
      attackEnergyCost: {MoveAttribute.rough: 1},
      reversalEnergyCost: {MoveAttribute.rough: 1},
      power: 7,

      speed: 1,
      heatDelta: 6,
      description: '荒々しい反則気味の一撃。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_normal_aerial_1',
      name: 'ミサイルキック',
      category: TechniqueCardCategory.normal,
      attribute: MoveAttribute.aerial,
      attackEnergyCost: {MoveAttribute.aerial: 2},
      reversalEnergyCost: {MoveAttribute.aerial: 1},
      power: 10,

      speed: 2,
      heatDelta: 5,
      description: '飛び技の基本形。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_normal_counter_1',
      name: 'カウンタースラップ',
      category: TechniqueCardCategory.normal,
      attribute: MoveAttribute.counter,
      attackEnergyCost: {MoveAttribute.counter: 1},
      reversalEnergyCost: {MoveAttribute.counter: 1},
      power: 6,

      speed: 1,
      heatDelta: 4,
      description: '返し技を軸にした技。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p6_normal_takedown',
      name: 'テイクダウン',
      category: TechniqueCardCategory.normal,
      attribute: MoveAttribute.throwMove,
      attackEnergyCost: {MoveAttribute.throwMove: 1},
      reversalEnergyCost: {MoveAttribute.throwMove: 1},
      power: 8,

      speed: 1,
      heatDelta: 4,
      targetState: TechniqueTargetState.stand,
      causesDown: true,
      description:
          '相手をダウンさせるだけの投げ技（フォール効果なし）。ダウン後の関節技'
          '連携に使う想定（Phase 6モデルデッキ用に追加）。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_sig_akari_1',
      name: '紅蓮ドロップキック',
      category: TechniqueCardCategory.signature,
      attribute: MoveAttribute.aerial,
      allowedWrestlerIds: [akari],
      minimumLevel: 2,
      attackEnergyCost: {MoveAttribute.aerial: 2},
      reversalEnergyCost: {MoveAttribute.aerial: 2},
      power: 16,

      speed: 4,
      heatDelta: 8,
      description: '火神アカリの固有技（サンプル）。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_sig_akari_2',
      name: '灼熱チョップ',
      category: TechniqueCardCategory.signature,
      attribute: MoveAttribute.strike,
      allowedWrestlerIds: [akari],
      minimumLevel: 2,
      attackEnergyCost: {MoveAttribute.strike: 2},
      reversalEnergyCost: {MoveAttribute.strike: 2},
      power: 14,

      speed: 3,
      heatDelta: 7,
      description: '火神アカリの固有技（サンプル）。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_sig_jack_1',
      name: '黒蝶スラム',
      category: TechniqueCardCategory.signature,
      attribute: MoveAttribute.throwMove,
      allowedWrestlerIds: [jack],
      minimumLevel: 2,
      attackEnergyCost: {MoveAttribute.throwMove: 2},
      reversalEnergyCost: {MoveAttribute.throwMove: 2},
      power: 15,

      speed: 3,
      heatDelta: 7,
      description: '黒蝶ジャックの固有技（サンプル）。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_sig_jack_2',
      name: '暗夜クラッチ',
      category: TechniqueCardCategory.signature,
      attribute: MoveAttribute.submission,
      allowedWrestlerIds: [jack],
      minimumLevel: 2,
      attackEnergyCost: {MoveAttribute.submission: 2},
      reversalEnergyCost: {MoveAttribute.submission: 2},
      power: 13,

      speed: 3,
      heatDelta: 7,
      description: '黒蝶ジャックの固有技（サンプル）。',
    ),

    // ============================================================
    // Phase 6モデルデッキ用カード（火神アカリ／白銀レイナ）
    //
    // ユーザー指示により、Phase 7へ進む前に「勝ち筋が明確に異なる2人分の
    // 正式なモデルデッキ」を用意して検証する。td_sig_akari_1/2は
    // minimumLevel: 2だが、Technique Match（Phase 3〜6）にはレベル変更
    // アクションが無くレベルは常に1固定（open questions 12番）のため、
    // 実戦では使用不可能なままになる。そのためモデルデッキでは
    // minimumLevel: 1の新規カードを使う（既存td_sig_*はDeck Builder上の
    // サンプルとして残す。削除・変更はしない）。
    // ============================================================
    const TechniqueDeckTechniqueCard(
      id: 'td_p6_akari_sig_kneestrike',
      name: '紅蓮ニーストライク',
      category: TechniqueCardCategory.signature,
      attribute: MoveAttribute.strike,
      allowedWrestlerIds: [akari],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.strike: 2},
      reversalEnergyCost: {MoveAttribute.strike: 1},
      power: 14,

      speed: 3,
      heatDelta: 6,
      targetState: TechniqueTargetState.stand,
      causesDown: true,
      description: '火神アカリの固有技。スタンド中の相手をダウンさせる打撃。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p6_akari_sig_german',
      name: '紅蓮ジャーマンスープレックス',
      category: TechniqueCardCategory.signature,
      attribute: MoveAttribute.throwMove,
      allowedWrestlerIds: [akari],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.throwMove: 2},
      reversalEnergyCost: {MoveAttribute.throwMove: 1},
      power: 16,

      speed: 4,
      heatDelta: 6,
      targetState: TechniqueTargetState.stand,
      causesDown: true,
      description: '火神アカリの固有技。スタンド中の相手をダウンさせる投げ技。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p6_akari_sig_suplex',
      name: '紅蓮フェニックススープレックス',
      category: TechniqueCardCategory.signature,
      attribute: MoveAttribute.throwMove,
      allowedWrestlerIds: [akari],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.throwMove: 2},
      reversalEnergyCost: {MoveAttribute.throwMove: 2},
      power: 15,

      speed: 3,
      heatDelta: 7,
      targetState: TechniqueTargetState.stand,
      causesDown: true,
      hasPinEffect: true,
      kickOutThreshold: 20,
      kickOutHpRate: 0.4,
      description: '火神アカリの固有技。ダウンを奪いつつフォールも狙える投げ技。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p6_akari_sig_lariat',
      name: '紅蓮ラリアット',
      category: TechniqueCardCategory.signature,
      attribute: MoveAttribute.strike,
      allowedWrestlerIds: [akari],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.strike: 2},
      reversalEnergyCost: {MoveAttribute.strike: 2},
      power: 17,

      speed: 4,
      heatDelta: 7,
      description: '火神アカリの固有技。純粋な高火力打撃。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p6_akari_sig_finalkick',
      name: '紅蓮ファイナルキック',
      category: TechniqueCardCategory.signature,
      attribute: MoveAttribute.strike,
      allowedWrestlerIds: [akari],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.strike: 3},
      reversalEnergyCost: {MoveAttribute.strike: 2},
      power: 18,

      speed: 5,
      heatDelta: 8,
      targetState: TechniqueTargetState.down,
      hasPinEffect: true,
      kickOutThreshold: 20,
      kickOutHpRate: 0.5,
      description: '火神アカリの固有技。ダウン中の相手に狙う主力フォール技。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p6_akari_fall_extra',
      name: '紅蓮バーニングプレス',
      category: TechniqueCardCategory.normal,
      attribute: MoveAttribute.throwMove,
      attackEnergyCost: {MoveAttribute.throwMove: 2},
      reversalEnergyCost: {MoveAttribute.throwMove: 1},
      power: 12,

      speed: 2,
      heatDelta: 5,
      targetState: TechniqueTargetState.down,
      hasPinEffect: true,
      kickOutThreshold: 20,
      kickOutHpRate: 0.5,
      description:
          'ダウン中の相手に狙うフォール技（通常技、汎用）。アカリのモデル'
          'デッキでは「調整枠」として1枚採用する。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p6_reina_sig_kneebar',
      name: '銀の腕ひしぎ十字固めEX',
      category: TechniqueCardCategory.signature,
      attribute: MoveAttribute.submission,
      allowedWrestlerIds: [reina],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.submission: 2},
      reversalEnergyCost: {MoveAttribute.submission: 1},
      power: 14,

      speed: 3,
      heatDelta: 6,
      targetState: TechniqueTargetState.any,
      hasSubmissionEffect: true,
      giveUpThreshold: 20,
      giveUpHpCost: 8,
      downBonusPower: 8,
      description: '白銀レイナの固有技。スタンドでも使えるが、ダウン中の方が効く関節技。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p6_reina_sig_brainbuster',
      name: '白銀ブレーンバスターEX',
      category: TechniqueCardCategory.signature,
      attribute: MoveAttribute.throwMove,
      allowedWrestlerIds: [reina],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.throwMove: 2},
      reversalEnergyCost: {MoveAttribute.throwMove: 1},
      power: 15,

      speed: 3,
      heatDelta: 6,
      targetState: TechniqueTargetState.stand,
      causesDown: true,
      description: '白銀レイナの固有技。スタンド中の相手をダウンさせる投げ技。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p6_reina_sig_camel',
      name: '氷結キャメルクラッチEX',
      category: TechniqueCardCategory.signature,
      attribute: MoveAttribute.submission,
      allowedWrestlerIds: [reina],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.submission: 2},
      reversalEnergyCost: {MoveAttribute.submission: 2},
      power: 13,

      speed: 3,
      heatDelta: 6,
      targetState: TechniqueTargetState.any,
      downBonusPower: 6,
      description: '白銀レイナの固有技。決着効果は無いが、ダウン中の相手に特に効く関節技。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p6_reina_sig_figurefour',
      name: '銀糸の足4の字固めEX',
      category: TechniqueCardCategory.signature,
      attribute: MoveAttribute.submission,
      allowedWrestlerIds: [reina],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.submission: 2},
      reversalEnergyCost: {MoveAttribute.submission: 2},
      power: 15,

      speed: 3,
      heatDelta: 7,
      targetState: TechniqueTargetState.down,
      hasSubmissionEffect: true,
      giveUpThreshold: 20,
      giveUpHpCost: 12,
      description: '白銀レイナの固有技。ダウン中の相手に狙う主力ギブアップ技。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p6_reina_sig_crossface',
      name: '白銀クロスフェイスEX',
      category: TechniqueCardCategory.signature,
      attribute: MoveAttribute.submission,
      allowedWrestlerIds: [reina],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.submission: 3},
      reversalEnergyCost: {MoveAttribute.submission: 2},
      power: 17,

      speed: 4,
      heatDelta: 8,
      targetState: TechniqueTargetState.any,
      downBonusPower: 10,
      description: '白銀レイナの固有技。決着効果は無いが、ダウン中の相手に特に効く高火力関節技。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p6_reina_giveup_extra',
      name: '銀氷アンクルホールド',
      category: TechniqueCardCategory.normal,
      attribute: MoveAttribute.submission,
      attackEnergyCost: {MoveAttribute.submission: 2},
      reversalEnergyCost: {MoveAttribute.submission: 1},
      power: 10,

      speed: 2,
      heatDelta: 5,
      targetState: TechniqueTargetState.down,
      hasSubmissionEffect: true,
      giveUpThreshold: 20,
      giveUpHpCost: 10,
      description:
          'ダウン中の相手に狙うギブアップ技（通常技、汎用）。レイナのモデル'
          'デッキでは「調整枠」として1枚採用する。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p6_misaki_sig_elbow',
      name: '豪腕エルボー',
      category: TechniqueCardCategory.signature,
      attribute: MoveAttribute.strike,
      allowedWrestlerIds: [misaki],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.strike: 2},
      reversalEnergyCost: {MoveAttribute.strike: 1},
      power: 16,

      speed: 4,
      heatDelta: 6,
      description: '豪田ミサキの固有技。一撃の重い打撃。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p6_misaki_sig_bodyslam',
      name: '豪田ボディスラム',
      category: TechniqueCardCategory.signature,
      attribute: MoveAttribute.throwMove,
      allowedWrestlerIds: [misaki],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.throwMove: 2},
      reversalEnergyCost: {MoveAttribute.throwMove: 1},
      power: 15,

      speed: 3,
      heatDelta: 6,
      targetState: TechniqueTargetState.stand,
      causesDown: true,
      description: '豪田ミサキの固有技。スタンド中の相手をダウンさせるパワー投げ技。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p6_misaki_sig_backdrop',
      name: '豪田バックドロップ',
      category: TechniqueCardCategory.signature,
      attribute: MoveAttribute.throwMove,
      allowedWrestlerIds: [misaki],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.throwMove: 2},
      reversalEnergyCost: {MoveAttribute.throwMove: 2},
      power: 17,

      speed: 4,
      heatDelta: 7,
      targetState: TechniqueTargetState.stand,
      causesDown: true,
      hasPinEffect: true,
      kickOutThreshold: 20,
      kickOutHpRate: 0.45,
      description: '豪田ミサキの固有技。ダウンを奪いつつフォールも狙えるパワー投げ技。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p6_misaki_sig_lariat',
      name: '豪田ラリアット',
      category: TechniqueCardCategory.signature,
      attribute: MoveAttribute.strike,
      allowedWrestlerIds: [misaki],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.strike: 2},
      reversalEnergyCost: {MoveAttribute.strike: 2},
      power: 18,

      speed: 5,
      heatDelta: 7,
      description: '豪田ミサキの固有技。純粋な高火力打撃。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p6_misaki_sig_powerbomb',
      name: '豪田パワーボム',
      category: TechniqueCardCategory.signature,
      attribute: MoveAttribute.throwMove,
      allowedWrestlerIds: [misaki],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.throwMove: 3},
      reversalEnergyCost: {MoveAttribute.throwMove: 2},
      power: 19,

      speed: 5,
      heatDelta: 8,
      targetState: TechniqueTargetState.down,
      hasPinEffect: true,
      kickOutThreshold: 20,
      kickOutHpRate: 0.5,
      description: '豪田ミサキの固有技。ダウン中の相手に狙う主力フォール技。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p6_misaki_fall_extra',
      name: '豪田デスバレーボム',
      category: TechniqueCardCategory.normal,
      attribute: MoveAttribute.throwMove,
      attackEnergyCost: {MoveAttribute.throwMove: 2},
      reversalEnergyCost: {MoveAttribute.throwMove: 1},
      power: 13,

      speed: 3,
      heatDelta: 5,
      targetState: TechniqueTargetState.down,
      hasPinEffect: true,
      kickOutThreshold: 20,
      kickOutHpRate: 0.5,
      description:
          'ダウン中の相手に狙うフォール技（通常技、汎用）。ミサキのモデル'
          'デッキでは「調整枠」として1枚採用する。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p6_jack_sig_lowblow',
      name: '暗夜ローブロー',
      category: TechniqueCardCategory.signature,
      attribute: MoveAttribute.rough,
      allowedWrestlerIds: [jack],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.rough: 2},
      reversalEnergyCost: {MoveAttribute.rough: 1},
      power: 13,

      speed: 3,
      heatDelta: 6,
      description: '黒蝶ジャックの固有技。反則気味の一撃。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p6_jack_sig_neckbreaker',
      name: '暗夜ネックブリーカー',
      category: TechniqueCardCategory.signature,
      attribute: MoveAttribute.rough,
      allowedWrestlerIds: [jack],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.rough: 2},
      reversalEnergyCost: {MoveAttribute.rough: 1},
      power: 15,

      speed: 3,
      heatDelta: 6,
      targetState: TechniqueTargetState.stand,
      causesDown: true,
      description: '黒蝶ジャックの固有技。スタンド中の相手をダウンさせる妨害技。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p6_jack_sig_clutch',
      name: '暗夜クラッチEX',
      category: TechniqueCardCategory.signature,
      attribute: MoveAttribute.submission,
      allowedWrestlerIds: [jack],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.submission: 2},
      reversalEnergyCost: {MoveAttribute.submission: 2},
      power: 14,

      speed: 3,
      heatDelta: 6,
      targetState: TechniqueTargetState.any,
      hasSubmissionEffect: true,
      giveUpThreshold: 20,
      giveUpHpCost: 8,
      downBonusPower: 8,
      description: '黒蝶ジャックの固有技。スタンドでも使えるが、ダウン中の方が効く絞め技。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p6_jack_sig_chair',
      name: '暗夜チェアショット',
      category: TechniqueCardCategory.signature,
      attribute: MoveAttribute.rough,
      allowedWrestlerIds: [jack],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.rough: 3},
      reversalEnergyCost: {MoveAttribute.rough: 2},
      power: 18,

      speed: 5,
      heatDelta: 8,
      description: '黒蝶ジャックの固有技。凶器を使った反則の高火力打撃。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p6_jack_sig_deathlock',
      name: '暗夜デスロック',
      category: TechniqueCardCategory.signature,
      attribute: MoveAttribute.submission,
      allowedWrestlerIds: [jack],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.submission: 2},
      reversalEnergyCost: {MoveAttribute.submission: 2},
      power: 16,

      speed: 4,
      heatDelta: 7,
      targetState: TechniqueTargetState.down,
      hasSubmissionEffect: true,
      giveUpThreshold: 20,
      giveUpHpCost: 12,
      description: '黒蝶ジャックの固有技。ダウン中の相手に狙う主力ギブアップ技。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p6_jack_giveup_extra',
      name: '暗夜スリーパーホールド',
      category: TechniqueCardCategory.normal,
      attribute: MoveAttribute.submission,
      attackEnergyCost: {MoveAttribute.submission: 2},
      reversalEnergyCost: {MoveAttribute.submission: 1},
      power: 10,

      speed: 2,
      heatDelta: 5,
      targetState: TechniqueTargetState.down,
      hasSubmissionEffect: true,
      giveUpThreshold: 20,
      giveUpHpCost: 10,
      description:
          'ダウン中の相手に狙うギブアップ技（通常技、汎用）。ジャックのモデル'
          'デッキでは「調整枠」として1枚採用する。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_fin_akari_1',
      name: '紅蓮フェニックスドライバー',
      category: TechniqueCardCategory.finisher,
      attribute: MoveAttribute.throwMove,
      allowedWrestlerIds: [akari],
      minimumLevel: 3,
      attackEnergyCost: {MoveAttribute.throwMove: 3},
      reversalEnergyCost: {MoveAttribute.throwMove: 4},
      power: 30,

      speed: 8,
      heatDelta: 10,
      hasFinisherEffect: true,
      finisherRequirements: {'minimumHeat': 40},
      description: '火神アカリのフィニッシャー（サンプル）。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_fin_akari_2',
      name: '灼熱インフェルノロック',
      category: TechniqueCardCategory.finisher,
      attribute: MoveAttribute.submission,
      allowedWrestlerIds: [akari],
      minimumLevel: 3,
      attackEnergyCost: {MoveAttribute.submission: 3},
      reversalEnergyCost: {MoveAttribute.submission: 4},
      power: 26,

      speed: 7,
      heatDelta: 10,
      hasFinisherEffect: true,
      finisherRequirements: {'minimumHeat': 40},
      description: '火神アカリのフィニッシャー（サンプル）。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_fin_jack_1',
      name: '黒蝶ジャックナイフ',
      category: TechniqueCardCategory.finisher,
      attribute: MoveAttribute.strike,
      allowedWrestlerIds: [jack],
      minimumLevel: 3,
      attackEnergyCost: {MoveAttribute.strike: 3},
      reversalEnergyCost: {MoveAttribute.strike: 4},
      power: 28,

      speed: 8,
      heatDelta: 10,
      hasFinisherEffect: true,
      finisherRequirements: {'minimumHeat': 40},
      description: '黒蝶ジャックのフィニッシャー（サンプル）。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_fin_jack_2',
      name: '暗夜デスバレー',
      category: TechniqueCardCategory.finisher,
      attribute: MoveAttribute.throwMove,
      allowedWrestlerIds: [jack],
      minimumLevel: 3,
      attackEnergyCost: {MoveAttribute.throwMove: 3},
      reversalEnergyCost: {MoveAttribute.throwMove: 4},
      power: 27,

      speed: 8,
      heatDelta: 10,
      hasFinisherEffect: true,
      finisherRequirements: {'minimumHeat': 40},
      description: '黒蝶ジャックのフィニッシャー（サンプル）。',
    ),

    // ============================================================
    // Phase 7モデルデッキ用フィニッシャーカード（火神アカリ／豪田ミサキ／
    // 白銀レイナ／黒蝶ジャック）
    //
    // ユーザー指示により、各レスラー3枚構成（1: targetState: any、
    // 2: 得意状態限定、3: 条件付きの高性能技）とし、発動条件
    // （finisherRequirements）はレスラーごとに変えた（アカリ:HEAT重視、
    // ミサキ:相手低HP重視、レイナ:相手ダウン重視、ジャック:自分低HP重視）。
    // 既存td_fin_*（minimumLevel: 3）はレベル変更アクション未実装のため
    // 実戦投入できず、モデルデッキでは使わない（minimumLevel: 1の新規
    // カードとして追加。既存td_fin_*は変更・削除しない）。
    //
    // 【Phase 7.5で追加】1000試合検証で「アカリ対アカリのミラー戦のみ
    // フィニッシャー宣言率1.0%」という個体差が判明した。原因はアカリの
    // 3枚すべてが`minimumHeat: 60`以上を要求しており、HEATの蓄積速度に
    // 対して条件が事実上機能していなかったこと（open questions O番）。
    // ユーザー指示により、HEAT数値そのもの（60→50等）は調整せず、
    // 「3枚とも違う役割にする」という条件の分散のみを行った。アカリ・
    // ミサキ・ジャックの2枚目（得意状態限定枠）から追加条件を外し
    // （targetStateの一致だけで使える「素直な決め技」にした）、3枚目
    // （条件付き高性能技）からもHEAT条件を外して相手HP／自分HPのみの
    // 条件へ変更した。白銀レイナはもともと3枚がHEAT／ダウン限定（無条件）／
    // ダウン+HPと分散していたため変更していない。
    // ============================================================
    const TechniqueDeckTechniqueCard(
      id: 'td_p7_akari_fin_burningdrive',
      name: '紅蓮バーニングドライブ',
      category: TechniqueCardCategory.finisher,
      attribute: MoveAttribute.strike,
      allowedWrestlerIds: [akari],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.strike: 3},
      power: 20,

      speed: 6,
      heatDelta: 10,
      hasFinisherEffect: true,
      finisherRequirements: {'minimumHeat': 60},
      description: '火神アカリのフィニッシャー。スタンド／ダウン問わず使える。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7_akari_fin_phoenixdriver',
      name: '紅蓮フェニックスドライバーEX',
      category: TechniqueCardCategory.finisher,
      attribute: MoveAttribute.throwMove,
      allowedWrestlerIds: [akari],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.throwMove: 3},
      power: 26,

      speed: 7,
      heatDelta: 10,
      targetState: TechniqueTargetState.stand,
      hasFinisherEffect: true,
      finisherRequirements: {},
      description: '火神アカリのフィニッシャー。スタンド中の相手に決めるお得意の一撃'
          '（Phase 7.5でHEAT条件を撤去。スタンド状態にさえできれば狙える）。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7_akari_fin_finalflame',
      name: '紅蓮ファイナルフレイム',
      category: TechniqueCardCategory.finisher,
      attribute: MoveAttribute.strike,
      allowedWrestlerIds: [akari],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.strike: 4},
      power: 28,

      speed: 8,
      heatDelta: 10,
      targetState: TechniqueTargetState.down,
      hasFinisherEffect: true,
      finisherRequirements: {'maximumOpponentHp': 60},
      description: '火神アカリのフィニッシャー。相手が弱っているダウン中に狙う止め'
          '（Phase 7.5でHEAT条件を撤去し、相手HP条件のみへ変更）。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7_misaki_fin_ironpress',
      name: '鋼鉄プレス',
      category: TechniqueCardCategory.finisher,
      attribute: MoveAttribute.throwMove,
      allowedWrestlerIds: [misaki],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.throwMove: 3},
      power: 20,

      speed: 6,
      heatDelta: 10,
      hasFinisherEffect: true,
      finisherRequirements: {'maximumOpponentHp': 50},
      description: '豪田ミサキのフィニッシャー。スタンド／ダウン問わず使える。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7_misaki_fin_gouda',
      name: '豪田ドライバーEX',
      category: TechniqueCardCategory.finisher,
      attribute: MoveAttribute.throwMove,
      allowedWrestlerIds: [misaki],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.throwMove: 3},
      power: 26,

      speed: 7,
      heatDelta: 10,
      targetState: TechniqueTargetState.down,
      hasFinisherEffect: true,
      finisherRequirements: {},
      description: '豪田ミサキのフィニッシャー。ダウン中の相手に決めるお得意の一撃'
          '（Phase 7.5で相手HP条件を撤去。ダウンさせられれば狙える）。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7_misaki_fin_ultimate',
      name: '鋼鉄アルティメットボム',
      category: TechniqueCardCategory.finisher,
      attribute: MoveAttribute.strike,
      allowedWrestlerIds: [misaki],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.strike: 4},
      power: 28,

      speed: 8,
      heatDelta: 10,
      targetState: TechniqueTargetState.down,
      hasFinisherEffect: true,
      finisherRequirements: {'maximumOpponentHp': 40, 'minimumHeat': 50},
      description: '豪田ミサキのフィニッシャー。条件は厳しいが最高火力を誇る。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7_reina_fin_silverwing',
      name: '銀翼ロック',
      category: TechniqueCardCategory.finisher,
      attribute: MoveAttribute.submission,
      allowedWrestlerIds: [reina],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.submission: 3},
      power: 18,

      speed: 6,
      heatDelta: 9,
      hasFinisherEffect: true,
      finisherRequirements: {'minimumHeat': 60},
      description: '白銀レイナのフィニッシャー。スタンド／ダウン問わず使える。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7_reina_fin_armbar_ex',
      name: '銀の腕ひしぎ十字固めEX改',
      category: TechniqueCardCategory.finisher,
      attribute: MoveAttribute.submission,
      allowedWrestlerIds: [reina],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.submission: 3},
      power: 24,

      speed: 7,
      heatDelta: 10,
      targetState: TechniqueTargetState.down,
      hasFinisherEffect: true,
      finisherRequirements: {'requiredOpponentState': 'down'},
      description: '白銀レイナのフィニッシャー。ダウン中の相手に対する高火力技。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7_reina_fin_absolute',
      name: '白銀アブソリュートロック',
      category: TechniqueCardCategory.finisher,
      attribute: MoveAttribute.submission,
      allowedWrestlerIds: [reina],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.submission: 4},
      power: 28,

      speed: 8,
      heatDelta: 10,
      targetState: TechniqueTargetState.down,
      hasFinisherEffect: true,
      finisherRequirements: {'requiredOpponentState': 'down', 'maximumOpponentHp': 50},
      description: '白銀レイナのフィニッシャー。条件は厳しいが最高火力を誇る。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7_jack_fin_blackbutterfly',
      name: '黒蝶乱舞',
      category: TechniqueCardCategory.finisher,
      attribute: MoveAttribute.rough,
      allowedWrestlerIds: [jack],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.rough: 3},
      power: 20,

      speed: 6,
      heatDelta: 9,
      hasFinisherEffect: true,
      finisherRequirements: {'maximumOwnHp': 40},
      description: '黒蝶ジャックのフィニッシャー。スタンド／ダウン問わず使える。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7_jack_fin_darkfall',
      name: '暗夜フォールEX',
      category: TechniqueCardCategory.finisher,
      attribute: MoveAttribute.submission,
      allowedWrestlerIds: [jack],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.submission: 3},
      power: 24,

      speed: 7,
      heatDelta: 10,
      targetState: TechniqueTargetState.down,
      hasFinisherEffect: true,
      finisherRequirements: {},
      description: '黒蝶ジャックのフィニッシャー。ダウン中の相手に決めるお得意の一撃'
          '（Phase 7.5で自分HP条件を撤去。ダウンさせられれば狙える）。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7_jack_fin_judgment',
      name: '漆黒ジャッジメント',
      category: TechniqueCardCategory.finisher,
      attribute: MoveAttribute.rough,
      allowedWrestlerIds: [jack],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.rough: 4},
      power: 28,

      speed: 8,
      heatDelta: 10,
      targetState: TechniqueTargetState.down,
      hasFinisherEffect: true,
      finisherRequirements: {'maximumOwnHp': 30, 'minimumHeat': 50},
      description: '黒蝶ジャックのフィニッシャー。条件は厳しいが最高火力を誇る。',
    ),

    // ============================================================
    // Phase 7A（正式モデルデータ）: 4人分の技カード（各12枚 = 通常技8・
    // 固有技2・フィニッシャー2）
    //
    // ユーザー指示により、今回はゲームバランス調整ではなく正式なモデル
    // データの実装が目的。技名はユーザー指定の一覧をそのまま使用した。
    // 数値（power/heatDelta/コスト等）は既存td_p6_*/td_p7_*系カードの
    // 相場感（通常技8前後・固有技14〜18・フィニッシャー20〜28）を踏襲した
    // 暫定値であり、正式なバランス調整はまだ行っていない（完了報告の
    // 「今後バランス調整が必要と思われるカード」参照）。
    //
    // フィニッシャーの発動条件（finisherRequirements）は、Phase 7.5で
    // 判明した「全員HEATのみで揃えると宣言率が偏る」問題を踏まえ、
    // レスラーごとに異なる条件軸を採用した（アカリ:HEAT、ミサキ:相手HP、
    // レイナ:HEAT、ジャック:自分HP）。2枚目はtargetStateによる状態限定の
    // みで追加数値条件を課さない、既存Phase 7.5モデルデッキと同じ設計。
    //
    // imagePathは技専用イラストが無いため全カードnull（フィールドのみ
    // 用意。技カード表示はアイコンへフォールバックする想定）。
    // ============================================================

    // ---- 火神アカリ（打撃・スピード型、フォール寄り） ----
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_akari_normal_elbow',
      name: 'エルボー',
      category: TechniqueCardCategory.normal,
      attribute: MoveAttribute.strike,
      attackEnergyCost: {MoveAttribute.strike: 1},
      reversalEnergyCost: {MoveAttribute.strike: 1},
      power: 8,

      speed: 1,
      heatDelta: 5,
      description: '火神アカリの基本打撃技。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_akari_normal_middlekick',
      name: 'ミドルキック',
      category: TechniqueCardCategory.normal,
      attribute: MoveAttribute.strike,
      attackEnergyCost: {MoveAttribute.strike: 1},
      reversalEnergyCost: {MoveAttribute.strike: 1},
      power: 8,

      speed: 1,
      heatDelta: 5,
      description: '火神アカリの基本打撃技。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_akari_normal_dropkick',
      name: 'ドロップキック',
      category: TechniqueCardCategory.normal,
      attribute: MoveAttribute.aerial,
      attackEnergyCost: {MoveAttribute.aerial: 1},
      reversalEnergyCost: {MoveAttribute.aerial: 1},
      power: 11,

      speed: 2,
      heatDelta: 5,
      targetState: TechniqueTargetState.stand,
      causesDown: true,
      description: '火神アカリの飛び技。スタンド中の相手をダウンさせる。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_akari_normal_runningknee',
      name: 'ランニングニー',
      category: TechniqueCardCategory.normal,
      attribute: MoveAttribute.strike,
      attackEnergyCost: {MoveAttribute.strike: 1},
      reversalEnergyCost: {MoveAttribute.strike: 1},
      power: 9,

      speed: 2,
      heatDelta: 5,
      description: '火神アカリの打撃技。助走をつけた膝蹴り。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_akari_normal_armwhip',
      name: 'アームホイップ',
      category: TechniqueCardCategory.normal,
      attribute: MoveAttribute.throwMove,
      attackEnergyCost: {MoveAttribute.throwMove: 1},
      reversalEnergyCost: {MoveAttribute.throwMove: 1},
      power: 8,

      speed: 1,
      heatDelta: 5,
      description: '火神アカリの投げ技。相手の腕を取って振り回す。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_akari_normal_crossbody',
      name: 'フライングクロスボディ',
      category: TechniqueCardCategory.normal,
      attribute: MoveAttribute.aerial,
      attackEnergyCost: {MoveAttribute.aerial: 2},
      reversalEnergyCost: {MoveAttribute.aerial: 1},
      power: 11,

      speed: 2,
      heatDelta: 5,
      targetState: TechniqueTargetState.down,
      hasPinEffect: true,
      kickOutThreshold: 20,
      kickOutHpRate: 0.45,
      description: '火神アカリの飛び技。ダウン中の相手に飛びついてフォールを狙う。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_akari_normal_swingddt',
      name: 'スイングDDT',
      category: TechniqueCardCategory.normal,
      attribute: MoveAttribute.throwMove,
      attackEnergyCost: {MoveAttribute.throwMove: 1},
      reversalEnergyCost: {MoveAttribute.throwMove: 1},
      power: 11,

      speed: 2,
      heatDelta: 5,
      targetState: TechniqueTargetState.stand,
      causesDown: true,
      description: '火神アカリの投げ技。スタンド中の相手をダウンさせる。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_akari_normal_forearm',
      name: 'フォアアーム',
      category: TechniqueCardCategory.normal,
      attribute: MoveAttribute.strike,
      attackEnergyCost: {MoveAttribute.strike: 1},
      reversalEnergyCost: {MoveAttribute.strike: 1},
      power: 8,

      speed: 1,
      heatDelta: 5,
      description: '火神アカリの基本打撃技。前腕による強打。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_akari_sig_phoenixarmdrag',
      name: 'フェニックス・アームドラッグ',
      category: TechniqueCardCategory.signature,
      attribute: MoveAttribute.throwMove,
      allowedWrestlerIds: ['wrestler_akari'],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.throwMove: 2},
      reversalEnergyCost: {MoveAttribute.throwMove: 1},
      power: 16,

      speed: 4,
      heatDelta: 7,
      description: '火神アカリの固有技。鮮やかな腕取り投げ。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_akari_sig_soulhighkick',
      name: 'ソウルハイキック',
      category: TechniqueCardCategory.signature,
      attribute: MoveAttribute.strike,
      allowedWrestlerIds: ['wrestler_akari'],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.strike: 2},
      reversalEnergyCost: {MoveAttribute.strike: 1},
      power: 17,

      speed: 4,
      heatDelta: 7,
      description: '火神アカリの固有技。魂を込めた高角度キック。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_akari_fin_phoenixsplash',
      name: 'フェニックススプラッシュ',
      category: TechniqueCardCategory.finisher,
      attribute: MoveAttribute.aerial,
      allowedWrestlerIds: ['wrestler_akari'],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.aerial: 3},
      power: 22,

      speed: 7,
      heatDelta: 9,
      hasFinisherEffect: true,
      finisherRequirements: {'minimumHeat': 50},
      description: '火神アカリのフィニッシャー。スタンド／ダウン問わず使える大技。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_akari_fin_redflarekick',
      name: 'レッドフレアキック',
      category: TechniqueCardCategory.finisher,
      attribute: MoveAttribute.strike,
      allowedWrestlerIds: ['wrestler_akari'],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.strike: 3},
      power: 26,

      speed: 7,
      heatDelta: 10,
      targetState: TechniqueTargetState.stand,
      hasFinisherEffect: true,
      finisherRequirements: {},
      description: '火神アカリのフィニッシャー。スタンド中の相手に決める渾身の一撃。',
    ),

    // ---- 豪田ミサキ（パワー・投げ型、フォール寄り） ----
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_misaki_normal_bodyslam',
      name: 'ボディスラム',
      category: TechniqueCardCategory.normal,
      attribute: MoveAttribute.throwMove,
      attackEnergyCost: {MoveAttribute.throwMove: 1},
      reversalEnergyCost: {MoveAttribute.throwMove: 1},
      power: 11,

      speed: 2,
      heatDelta: 5,
      targetState: TechniqueTargetState.stand,
      causesDown: true,
      description: '豪田ミサキの投げ技。スタンド中の相手を叩きつけてダウンさせる。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_misaki_normal_shouldertackle',
      name: 'ショルダータックル',
      category: TechniqueCardCategory.normal,
      attribute: MoveAttribute.strike,
      attackEnergyCost: {MoveAttribute.strike: 1},
      reversalEnergyCost: {MoveAttribute.strike: 1},
      power: 8,

      speed: 1,
      heatDelta: 5,
      description: '豪田ミサキの基本打撃技。体当たり。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_misaki_normal_lariat',
      name: 'ラリアット',
      category: TechniqueCardCategory.normal,
      attribute: MoveAttribute.strike,
      attackEnergyCost: {MoveAttribute.strike: 1},
      reversalEnergyCost: {MoveAttribute.strike: 1},
      power: 9,

      speed: 2,
      heatDelta: 5,
      description: '豪田ミサキの基本打撃技。全力の腕による薙ぎ払い。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_misaki_normal_backdrop',
      name: 'バックドロップ',
      category: TechniqueCardCategory.normal,
      attribute: MoveAttribute.throwMove,
      attackEnergyCost: {MoveAttribute.throwMove: 1},
      reversalEnergyCost: {MoveAttribute.throwMove: 1},
      power: 11,

      speed: 2,
      heatDelta: 5,
      targetState: TechniqueTargetState.stand,
      causesDown: true,
      description: '豪田ミサキの投げ技。スタンド中の相手を反り投げでダウンさせる。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_misaki_normal_brainbuster',
      name: 'ブレーンバスター',
      category: TechniqueCardCategory.normal,
      attribute: MoveAttribute.throwMove,
      attackEnergyCost: {MoveAttribute.throwMove: 2},
      reversalEnergyCost: {MoveAttribute.throwMove: 1},
      power: 11,

      speed: 2,
      heatDelta: 5,
      targetState: TechniqueTargetState.down,
      hasPinEffect: true,
      kickOutThreshold: 20,
      kickOutHpRate: 0.45,
      description: '豪田ミサキの投げ技。ダウン中の相手に叩き込みフォールを狙う。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_misaki_normal_powerslam',
      name: 'パワースラム',
      category: TechniqueCardCategory.normal,
      attribute: MoveAttribute.throwMove,
      attackEnergyCost: {MoveAttribute.throwMove: 1},
      reversalEnergyCost: {MoveAttribute.throwMove: 1},
      power: 9,

      speed: 2,
      heatDelta: 5,
      description: '豪田ミサキの投げ技。力任せに叩きつける。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_misaki_normal_kneelift',
      name: 'ニーリフト',
      category: TechniqueCardCategory.normal,
      attribute: MoveAttribute.strike,
      attackEnergyCost: {MoveAttribute.strike: 1},
      reversalEnergyCost: {MoveAttribute.strike: 1},
      power: 8,

      speed: 1,
      heatDelta: 5,
      description: '豪田ミサキの基本打撃技。膝を突き上げる。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_misaki_normal_spinebuster',
      name: 'スパインバスター',
      category: TechniqueCardCategory.normal,
      attribute: MoveAttribute.throwMove,
      attackEnergyCost: {MoveAttribute.throwMove: 1},
      reversalEnergyCost: {MoveAttribute.throwMove: 1},
      power: 11,

      speed: 2,
      heatDelta: 5,
      targetState: TechniqueTargetState.stand,
      causesDown: true,
      description: '豪田ミサキの投げ技。スタンド中の相手を背中から叩きつける。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_misaki_sig_powerbomb',
      name: 'パワーボム',
      category: TechniqueCardCategory.signature,
      attribute: MoveAttribute.throwMove,
      allowedWrestlerIds: ['wrestler_misaki'],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.throwMove: 2},
      reversalEnergyCost: {MoveAttribute.throwMove: 1},
      power: 16,

      speed: 4,
      heatDelta: 7,
      description: '豪田ミサキの固有技。相手を担ぎ上げて叩きつけるパワー技。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_misaki_sig_giantslam',
      name: 'ジャイアントスラム',
      category: TechniqueCardCategory.signature,
      attribute: MoveAttribute.throwMove,
      allowedWrestlerIds: ['wrestler_misaki'],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.throwMove: 2},
      reversalEnergyCost: {MoveAttribute.throwMove: 1},
      power: 17,

      speed: 4,
      heatDelta: 7,
      description: '豪田ミサキの固有技。全体重を乗せた豪快な叩きつけ。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_misaki_fin_goudadriver',
      name: '豪田ドライバー',
      category: TechniqueCardCategory.finisher,
      attribute: MoveAttribute.throwMove,
      allowedWrestlerIds: ['wrestler_misaki'],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.throwMove: 3},
      power: 22,

      speed: 7,
      heatDelta: 9,
      hasFinisherEffect: true,
      finisherRequirements: {'maximumOpponentHp': 50},
      description: '豪田ミサキのフィニッシャー。スタンド／ダウン問わず使える大技。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_misaki_fin_lastpowerbomb',
      name: 'ラストパワーボム',
      category: TechniqueCardCategory.finisher,
      attribute: MoveAttribute.throwMove,
      allowedWrestlerIds: ['wrestler_misaki'],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.throwMove: 3},
      power: 26,

      speed: 7,
      heatDelta: 10,
      targetState: TechniqueTargetState.down,
      hasFinisherEffect: true,
      finisherRequirements: {},
      description: '豪田ミサキのフィニッシャー。ダウン中の相手に決める渾身の一撃。',
    ),

    // ---- 白銀レイナ（関節・テクニカル型、ギブアップ寄り） ----
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_reina_normal_elbow',
      name: 'エルボー',
      category: TechniqueCardCategory.normal,
      attribute: MoveAttribute.strike,
      attackEnergyCost: {MoveAttribute.strike: 1},
      reversalEnergyCost: {MoveAttribute.strike: 1},
      power: 8,

      speed: 1,
      heatDelta: 5,
      description: '白銀レイナの基本打撃技。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_reina_normal_dragonscrew',
      name: 'ドラゴンスクリュー',
      category: TechniqueCardCategory.normal,
      attribute: MoveAttribute.throwMove,
      attackEnergyCost: {MoveAttribute.throwMove: 1},
      reversalEnergyCost: {MoveAttribute.throwMove: 1},
      power: 11,

      speed: 2,
      heatDelta: 5,
      targetState: TechniqueTargetState.stand,
      causesDown: true,
      description: '白銀レイナの投げ技。足を捻り上げてダウンを奪う。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_reina_normal_armbreaker',
      name: 'アームブリーカー',
      category: TechniqueCardCategory.normal,
      attribute: MoveAttribute.submission,
      attackEnergyCost: {MoveAttribute.submission: 1},
      reversalEnergyCost: {MoveAttribute.submission: 1},
      power: 8,

      speed: 1,
      heatDelta: 5,
      description: '白銀レイナの関節技。腕を極める。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_reina_normal_headlock',
      name: 'ヘッドロック',
      category: TechniqueCardCategory.normal,
      attribute: MoveAttribute.submission,
      attackEnergyCost: {MoveAttribute.submission: 1},
      reversalEnergyCost: {MoveAttribute.submission: 1},
      power: 8,

      speed: 1,
      heatDelta: 5,
      description: '白銀レイナの関節技。頭部を固める基本ホールド。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_reina_normal_droptoehold',
      name: 'ドロップトーホールド',
      category: TechniqueCardCategory.normal,
      attribute: MoveAttribute.throwMove,
      attackEnergyCost: {MoveAttribute.throwMove: 1},
      reversalEnergyCost: {MoveAttribute.throwMove: 1},
      power: 11,

      speed: 2,
      heatDelta: 5,
      targetState: TechniqueTargetState.stand,
      causesDown: true,
      description: '白銀レイナの投げ技。足を取って倒し込みダウンを奪う。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_reina_normal_udehishigi',
      name: '腕ひしぎ',
      category: TechniqueCardCategory.normal,
      attribute: MoveAttribute.submission,
      attackEnergyCost: {MoveAttribute.submission: 2},
      reversalEnergyCost: {MoveAttribute.submission: 1},
      power: 11,

      speed: 2,
      heatDelta: 5,
      targetState: TechniqueTargetState.down,
      hasSubmissionEffect: true,
      giveUpThreshold: 20,
      giveUpHpCost: 10,
      description: '白銀レイナの関節技。ダウン中の相手の腕を極めてギブアップを狙う。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_reina_normal_figurefour',
      name: '足四の字',
      category: TechniqueCardCategory.normal,
      attribute: MoveAttribute.submission,
      attackEnergyCost: {MoveAttribute.submission: 1},
      reversalEnergyCost: {MoveAttribute.submission: 1},
      power: 9,

      speed: 2,
      heatDelta: 5,
      downBonusPower: 4,
      description: '白銀レイナの関節技。足を絡めて固める。ダウン中の相手に特に効く。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_reina_normal_sideheadlock',
      name: 'サイドヘッドロック',
      category: TechniqueCardCategory.normal,
      attribute: MoveAttribute.submission,
      attackEnergyCost: {MoveAttribute.submission: 1},
      reversalEnergyCost: {MoveAttribute.submission: 1},
      power: 8,

      speed: 1,
      heatDelta: 5,
      description: '白銀レイナの関節技。横から頭部を固める。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_reina_sig_crossface',
      name: '白銀クロスフェイス',
      category: TechniqueCardCategory.signature,
      attribute: MoveAttribute.submission,
      allowedWrestlerIds: ['wrestler_reina'],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.submission: 2},
      reversalEnergyCost: {MoveAttribute.submission: 1},
      power: 16,

      speed: 4,
      heatDelta: 7,
      description: '白銀レイナの固有技。顔面を極める高難度の関節技。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_reina_sig_figurefour_lock',
      name: 'フィギュアフォー',
      category: TechniqueCardCategory.signature,
      attribute: MoveAttribute.submission,
      allowedWrestlerIds: ['wrestler_reina'],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.submission: 2},
      reversalEnergyCost: {MoveAttribute.submission: 1},
      power: 17,

      speed: 4,
      heatDelta: 7,
      description: '白銀レイナの固有技。足を絡めて極める代名詞のホールド。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_reina_fin_icelock',
      name: 'アイスロック',
      category: TechniqueCardCategory.finisher,
      attribute: MoveAttribute.submission,
      allowedWrestlerIds: ['wrestler_reina'],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.submission: 3},
      power: 22,

      speed: 7,
      heatDelta: 9,
      hasFinisherEffect: true,
      finisherRequirements: {'minimumHeat': 50},
      description: '白銀レイナのフィニッシャー。スタンド／ダウン問わず使える大技。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_reina_fin_eternalcross',
      name: 'エターナルクロス',
      category: TechniqueCardCategory.finisher,
      attribute: MoveAttribute.submission,
      allowedWrestlerIds: ['wrestler_reina'],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.submission: 3},
      power: 26,

      speed: 7,
      heatDelta: 10,
      targetState: TechniqueTargetState.down,
      hasFinisherEffect: true,
      finisherRequirements: {},
      description: '白銀レイナのフィニッシャー。ダウン中の相手に決める渾身の一撃。',
    ),

    // ---- 黒蝶ジャック（ラフファイト・関節型、ギブアップ寄り） ----
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_jack_normal_lowblow',
      name: 'ローブロー',
      category: TechniqueCardCategory.normal,
      attribute: MoveAttribute.rough,
      attackEnergyCost: {MoveAttribute.rough: 1},
      reversalEnergyCost: {MoveAttribute.rough: 1},
      power: 8,

      speed: 1,
      heatDelta: 5,
      description: '黒蝶ジャックの反則気味の一撃。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_jack_normal_weapon',
      name: '凶器攻撃',
      category: TechniqueCardCategory.normal,
      attribute: MoveAttribute.rough,
      attackEnergyCost: {MoveAttribute.rough: 1},
      reversalEnergyCost: {MoveAttribute.rough: 1},
      power: 11,

      speed: 2,
      heatDelta: 5,
      targetState: TechniqueTargetState.stand,
      causesDown: true,
      description: '黒蝶ジャックの反則技。凶器でスタンド中の相手をダウンさせる。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_jack_normal_ddt',
      name: 'DDT',
      category: TechniqueCardCategory.normal,
      attribute: MoveAttribute.throwMove,
      attackEnergyCost: {MoveAttribute.throwMove: 1},
      reversalEnergyCost: {MoveAttribute.throwMove: 1},
      power: 11,

      speed: 2,
      heatDelta: 5,
      targetState: TechniqueTargetState.stand,
      causesDown: true,
      description: '黒蝶ジャックの投げ技。頭部を叩きつけてダウンを奪う。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_jack_normal_choke',
      name: 'チョーク',
      category: TechniqueCardCategory.normal,
      attribute: MoveAttribute.submission,
      attackEnergyCost: {MoveAttribute.submission: 1},
      reversalEnergyCost: {MoveAttribute.submission: 1},
      power: 8,

      speed: 1,
      heatDelta: 5,
      description: '黒蝶ジャックの反則気味の絞め技。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_jack_normal_ironclaw',
      name: 'アイアンクロー',
      category: TechniqueCardCategory.normal,
      attribute: MoveAttribute.submission,
      attackEnergyCost: {MoveAttribute.submission: 2},
      reversalEnergyCost: {MoveAttribute.submission: 1},
      power: 11,

      speed: 2,
      heatDelta: 5,
      targetState: TechniqueTargetState.down,
      hasSubmissionEffect: true,
      giveUpThreshold: 20,
      giveUpHpCost: 10,
      description: '黒蝶ジャックの関節技。ダウン中の相手の顔面を掴んでギブアップを狙う。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_jack_normal_neckhanging',
      name: 'ネックハンギング',
      category: TechniqueCardCategory.normal,
      attribute: MoveAttribute.submission,
      attackEnergyCost: {MoveAttribute.submission: 1},
      reversalEnergyCost: {MoveAttribute.submission: 1},
      power: 9,

      speed: 2,
      heatDelta: 5,
      downBonusPower: 4,
      description: '黒蝶ジャックの絞め技。ダウン中の相手に特に効く。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_jack_normal_facestomp',
      name: '顔面踏みつけ',
      category: TechniqueCardCategory.normal,
      attribute: MoveAttribute.rough,
      attackEnergyCost: {MoveAttribute.rough: 1},
      reversalEnergyCost: {MoveAttribute.rough: 1},
      power: 8,

      speed: 1,
      heatDelta: 5,
      description: '黒蝶ジャックの反則気味の一撃。ダウン中の相手を踏みつける。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_jack_normal_elbow',
      name: 'エルボー',
      category: TechniqueCardCategory.normal,
      attribute: MoveAttribute.strike,
      attackEnergyCost: {MoveAttribute.strike: 1},
      reversalEnergyCost: {MoveAttribute.strike: 1},
      power: 8,

      speed: 1,
      heatDelta: 5,
      description: '黒蝶ジャックの基本打撃技。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_jack_sig_blackddt',
      name: 'ブラックDDT',
      category: TechniqueCardCategory.signature,
      attribute: MoveAttribute.throwMove,
      allowedWrestlerIds: ['wrestler_jack'],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.throwMove: 2},
      reversalEnergyCost: {MoveAttribute.throwMove: 1},
      power: 16,

      speed: 4,
      heatDelta: 7,
      description: '黒蝶ジャックの固有技。捻りを加えた変形DDT。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_jack_sig_darkneck',
      name: 'ダークネックロック',
      category: TechniqueCardCategory.signature,
      attribute: MoveAttribute.submission,
      allowedWrestlerIds: ['wrestler_jack'],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.submission: 2},
      reversalEnergyCost: {MoveAttribute.submission: 1},
      power: 17,

      speed: 4,
      heatDelta: 7,
      description: '黒蝶ジャックの固有技。首を絞め上げる嫌らしいホールド。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_jack_fin_blackbutterfly',
      name: 'ブラックバタフライ',
      category: TechniqueCardCategory.finisher,
      attribute: MoveAttribute.rough,
      allowedWrestlerIds: ['wrestler_jack'],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.rough: 3},
      power: 22,

      speed: 7,
      heatDelta: 9,
      hasFinisherEffect: true,
      finisherRequirements: {'maximumOwnHp': 40},
      description: '黒蝶ジャックのフィニッシャー。スタンド／ダウン問わず使える大技。',
    ),
    const TechniqueDeckTechniqueCard(
      id: 'td_p7a_jack_fin_darkend',
      name: 'ダークエンド',
      category: TechniqueCardCategory.finisher,
      attribute: MoveAttribute.submission,
      allowedWrestlerIds: ['wrestler_jack'],
      minimumLevel: 1,
      attackEnergyCost: {MoveAttribute.submission: 3},
      power: 26,

      speed: 7,
      heatDelta: 10,
      targetState: TechniqueTargetState.down,
      hasFinisherEffect: true,
      finisherRequirements: {},
      description: '黒蝶ジャックのフィニッシャー。ダウン中の相手に決める渾身の一撃。',
    ),
  ];

  final energies = [
    for (final attribute in MoveAttribute.values)
      TechniqueEnergyCard(
        id: 'td_energy_${attribute.name}',
        attribute: attribute,
        name: '${moveAttributeLabel(attribute)}エネルギー',
      ),
  ];

  const defenseCards = [
    TechniqueDefenseCard(
      id: 'td_escape_1',
      name: 'エスケープ',
      type: TechniqueDeckCardType.escape,
      description: 'フィニッシャー発動をキャンセルする（サンプル）。',
    ),
    TechniqueDefenseCard(
      id: 'td_reversal_1',
      name: 'リバーサル',
      type: TechniqueDeckCardType.reversal,
      description: 'フィニッシャー発動をキャンセルする（サンプル、効果未実装）。',
    ),
    TechniqueDefenseCard(
      id: 'td_kickout_normal_1',
      name: 'キックアウト',
      type: TechniqueDeckCardType.kickOut,
      kickOutCategory: KickOutCardCategory.normal,
      description: '通常のフォールから脱出する（サンプル）。',
    ),
    TechniqueDefenseCard(
      id: 'td_kickout_special_1',
      name: 'ラストスタンド',
      type: TechniqueDeckCardType.kickOut,
      kickOutCategory: KickOutCardCategory.finisherEscape,
      description: '成功したフィニッシャーから脱出する（サンプル）。',
    ),
    TechniqueDefenseCard(
      id: 'td_ropebreak_1',
      name: 'ロープブレイク',
      type: TechniqueDeckCardType.ropeBreak,
      description: 'ギブアップから脱出する（サンプル）。',
    ),
  ];

  return TechniqueDeckCardCatalog(
    techniques: techniques,
    energies: energies,
    defenseCards: defenseCards,
  );
}
