import '../wrestler_editor/models.dart';
import 'level_match_engine.dart' show TechniqueResourceCard;

/// Ver.0.5: レスラーごとの技構成に合わせた30枚デッキ自動生成サービス。
///
/// 将来の手動デッキ編集に備え、生成方式（自動 / カスタム）を型で区別する。

enum DeckSource { autoGenerated, custom }

const int kDeckSize = 30;

/// デッキ生成結果。属性別枚数・採用理由・カード実体を保持する。
class DeckBuildResult {
  DeckBuildResult({
    required this.source,
    required this.counts,
    required this.cards,
    required this.attributeReasons,
    required this.usedAttributes,
    required this.usedFallback,
    this.failureReason,
  });

  final DeckSource source;
  final Map<MoveAttribute, int> counts;
  final List<TechniqueResourceCard> cards;

  /// 属性ごとに「なぜ入っているか」を示す簡易説明。
  final Map<MoveAttribute, List<String>> attributeReasons;
  final Set<MoveAttribute> usedAttributes;
  final bool usedFallback;
  final String? failureReason;

  bool get isValid => cards.length == kDeckSize;

  Map<String, dynamic> toJson() => {
    'source': source.name,
    'total': cards.length,
    'counts': {
      for (final entry in counts.entries) entry.key.name: entry.value,
    },
    'usedAttributes': usedAttributes.map((item) => item.name).toList(),
    'attributeReasons': {
      for (final entry in attributeReasons.entries)
        entry.key.name: entry.value,
    },
    'usedFallback': usedFallback,
    if (failureReason != null) 'failureReason': failureReason,
  };
}

class LevelMatchDeckBuilder {
  const LevelMatchDeckBuilder();

  /// 通常技のレベル別重み。
  int _levelWeight(int level) => level <= 1 ? 3 : 2;

  DeckBuildResult build({
    required WrestlerDefinition wrestler,
    required Map<String, MoveDefinition> moves,
    required String owner,
  }) {
    final weights = <MoveAttribute, double>{
      for (final attribute in MoveAttribute.values) attribute: 0,
    };
    final reasons = <MoveAttribute, List<String>>{
      for (final attribute in MoveAttribute.values) attribute: <String>[],
    };
    final minimums = <MoveAttribute, int>{
      for (final attribute in MoveAttribute.values) attribute: 0,
    };

    void addWeight(MoveAttribute attribute, double amount, String reason) {
      weights[attribute] = weights[attribute]! + amount;
      if (!reasons[attribute]!.contains(reason)) reasons[attribute]!.add(reason);
    }

    void raiseMinimum(MoveAttribute attribute, int value) {
      if (value > minimums[attribute]!) minimums[attribute] = value;
    }

    for (final level in wrestler.levels) {
      final ids = <MapEntry<String, int>>[
        for (final id in level.moveIds) MapEntry(id, _levelWeight(level.level)),
        if (level.counterMoveId != null) MapEntry(level.counterMoveId!, 1),
        if (level.finisherId != null) MapEntry(level.finisherId!, 2),
      ];
      for (final entry in ids) {
        final move = moves[entry.key];
        if (move == null) continue;
        final isFinisher = move.category == MoveCategory.finisher;
        final isCounter = move.category == MoveCategory.counter;
        for (final cost in move.requiredCards.entries) {
          if (cost.value <= 0) continue;
          addWeight(cost.key, entry.value * cost.value.toDouble(), move.name);
          if (isFinisher) {
            // フィニッシャー必須属性は「最大必要枚数＋1」以上。
            raiseMinimum(cost.key, cost.value + 1);
          }
          if (isCounter) {
            raiseMinimum(cost.key, 2);
          }
        }
        for (final discard in move.discardAfterUse.entries) {
          if (discard.value <= 0) continue;
          addWeight(discard.key, discard.value.toDouble(), '${move.name}(破棄)');
          raiseMinimum(discard.key, discard.value + 1);
        }
      }

      // 解放条件で参照する属性。
      final unlock = level.unlockCondition;
      if (unlock != null) {
        for (final condition in unlock.conditions) {
          final attribute = condition.attribute;
          if (attribute != null) {
            addWeight(attribute, 1, 'Lv.${level.level}解放条件');
          }
        }
      }
    }

    // Ver.0.7.2: レスラータイプ別バイアスで“プレイフィール”を差別化。
    for (final entry in _typeBias(wrestler.type).entries) {
      if (weights[entry.key]! > 0) {
        weights[entry.key] = weights[entry.key]! * entry.value;
      }
    }

    final usedAttributes = <MoveAttribute>{
      for (final attribute in MoveAttribute.values)
        if (weights[attribute]! > 0 || minimums[attribute]! > 0) attribute,
    };

    // 使用される属性は最低3枚。
    for (final attribute in usedAttributes) {
      raiseMinimum(attribute, 3);
    }

    final counts = _distribute(weights, minimums, usedAttributes);
    final usedFallback = counts == null;
    final resolved = counts ?? _fallbackCounts();

    var serial = 0;
    final cards = <TechniqueResourceCard>[
      for (final attribute in MoveAttribute.values)
        for (var i = 0; i < (resolved[attribute] ?? 0); i++)
          TechniqueResourceCard('$owner-${serial++}', attribute),
    ];

    return DeckBuildResult(
      source: DeckSource.autoGenerated,
      counts: resolved,
      cards: cards,
      attributeReasons: reasons,
      usedAttributes: usedAttributes,
      usedFallback: usedFallback,
      failureReason: usedFallback
          ? '技コストを集計できなかったため、均等30枚でフォールバックしました'
          : null,
    );
  }

  /// Ver.0.8.0 energyモード：技カード（手札から使用・使用後は捨て札）と
  /// 技エネルギーカード（場にセット）を混在させたデッキを生成する。
  /// 属性配分は classic と同じ重み計算（build）を再利用し、classic側の
  /// アルゴリズムには一切手を加えない。返（counter）属性は返し技を発動する
  /// 権利＝エネルギー専用として扱い、技カード化しない。
  DeckBuildResult buildEnergyMode({
    required WrestlerDefinition wrestler,
    required Map<String, MoveDefinition> moves,
    required String owner,
    double techniqueCardRatio = 0.4,
  }) {
    final base = build(wrestler: wrestler, moves: moves, owner: owner);
    var serial = 0;
    final cards = <TechniqueResourceCard>[
      for (final attribute in MoveAttribute.values)
        for (var i = 0; i < (base.counts[attribute] ?? 0); i++)
          _cardFor(
            owner,
            serial++,
            attribute,
            i,
            base.counts[attribute] ?? 0,
            techniqueCardRatio,
            wrestler,
            moves,
          ),
    ];
    return DeckBuildResult(
      source: base.source,
      counts: base.counts,
      cards: cards,
      attributeReasons: base.attributeReasons,
      usedAttributes: base.usedAttributes,
      usedFallback: base.usedFallback,
      failureReason: base.failureReason,
    );
  }

  TechniqueResourceCard _cardFor(
    String owner,
    int serial,
    MoveAttribute attribute,
    int indexWithinAttribute,
    int totalForAttribute,
    double techniqueCardRatio,
    WrestlerDefinition wrestler,
    Map<String, MoveDefinition> moves,
  ) {
    final id = '$owner-$serial';
    // 返エネルギーは常に純粋なエネルギーカード（返し技を発動する権利）。
    if (attribute == MoveAttribute.counter) {
      return TechniqueResourceCard(id, attribute);
    }
    final techniqueCount = (totalForAttribute * techniqueCardRatio).round();
    if (indexWithinAttribute >= techniqueCount) {
      return TechniqueResourceCard(id, attribute);
    }
    final ownId = wrestler.basicMoveIds[attribute];
    final moveId = (ownId != null && moves.containsKey(ownId))
        ? ownId
        : moves.values
            .firstWhere(
              (m) => m.category == MoveCategory.basic && m.attribute == attribute,
              orElse: () => moves.values.first,
            )
            .id;
    return TechniqueResourceCard(id, attribute, techniqueMoveId: moveId);
  }

  /// 重みと最低保証から30枚を配分する。破綻したら null（フォールバックへ）。
  Map<MoveAttribute, int>? _distribute(
    Map<MoveAttribute, double> weights,
    Map<MoveAttribute, int> minimums,
    Set<MoveAttribute> usedAttributes,
  ) {
    if (usedAttributes.isEmpty) return null;
    final counts = <MoveAttribute, int>{
      for (final attribute in MoveAttribute.values)
        attribute: minimums[attribute] ?? 0,
    };
    var used = counts.values.fold<int>(0, (sum, value) => sum + value);
    if (used > kDeckSize) return null; // 最低保証が30を超過 → フォールバック。

    var remaining = kDeckSize - used;
    final totalWeight = usedAttributes.fold<double>(
      0,
      (sum, attribute) => sum + weights[attribute]!,
    );
    if (totalWeight <= 0) {
      // 重みが取れない場合は使用属性へ均等配分。
      final list = usedAttributes.toList();
      var index = 0;
      while (remaining > 0) {
        counts[list[index % list.length]] =
            counts[list[index % list.length]]! + 1;
        index++;
        remaining--;
      }
      return counts;
    }

    // 最大剰余法で比例配分。
    final quotas = <MoveAttribute, double>{
      for (final attribute in usedAttributes)
        attribute: remaining * (weights[attribute]! / totalWeight),
    };
    final remainders = <MoveAttribute, double>{};
    for (final attribute in usedAttributes) {
      final floorValue = quotas[attribute]!.floor();
      counts[attribute] = counts[attribute]! + floorValue;
      remaining -= floorValue;
      remainders[attribute] = quotas[attribute]! - floorValue;
    }
    final ordered = usedAttributes.toList()
      ..sort((a, b) => remainders[b]!.compareTo(remainders[a]!));
    var index = 0;
    while (remaining > 0 && ordered.isNotEmpty) {
      final attribute = ordered[index % ordered.length];
      counts[attribute] = counts[attribute]! + 1;
      remaining--;
      index++;
    }
    return counts;
  }

  /// レスラータイプ別の属性重みバイアス（1.0=中立）。
  Map<MoveAttribute, double> _typeBias(EditorWrestlerType type) => switch (type) {
    // Ver.0.7.2: 強者を過度に増幅しないよう控えめに。ジャック(heel)は厚めに。
    EditorWrestlerType.power => {MoveAttribute.throwMove: 1.05},
    EditorWrestlerType.heel => {MoveAttribute.rough: 1.6},
    EditorWrestlerType.technician => {MoveAttribute.submission: 1.4},
    EditorWrestlerType.highSpeed => {
      MoveAttribute.strike: 1.3,
      MoveAttribute.aerial: 1.4,
    },
    // Ver.0.7.3: アカリは打撃技＋打撃フィニッシャー主体。空中カードは死札に
    // なりやすいので打撃へ寄せ、切り札の組み立てと手数を安定させる。
    EditorWrestlerType.babyface => {
      MoveAttribute.strike: 1.5,
      MoveAttribute.throwMove: 1.2,
    },
    EditorWrestlerType.striker => {MoveAttribute.strike: 1.4},
    _ => const {},
  };

  Map<MoveAttribute, int> _fallbackCounts() {
    // 6属性へ均等（5枚ずつ）= 30枚。
    return {for (final attribute in MoveAttribute.values) attribute: 5};
  }
}
